### ISSUE TITLE
Avoid the use of a wildcard (i.e., *) imports in Java code

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#10]
There are some Java classes, such as `CommandOutputSummary.java`, that contain wildcard imports. My preference would be to eliminate this type of import and instead explicitly import those Java classes that are under use. If there is a case when, for instance, all of the Java classes in a package are in use, then I would still prefer to import them all explicitly at the top of the file. Finally, when I edit these files, my linting configuration picks these up as errors. Is there a reason why these linting errors are not breaking the build?

**Comment by Michionlion** [comment]
The checkstyle configuration for the gradle build has some specific exceptions for certain rules -- I'll look into making these line up with a standard convention such as Google's. I agree that star imports should be refactored.

**Comment by gkapfham** [comment]
Great, thanks for looking into this issue @Michionlion. I should also note that there are a few classes for which my linter is complaining about indentation --- and then others in which I do not see this issue even though the indentation looks the same. Perhaps sometime later this week we can meet and discuss the coding style guide for this plugin. Again, thanks for your work on this --- it is really great!

**Comment by Michionlion** [comment]
Okay, I've changed everything to conform to the default google_checks.xml available from the checkstyle repository ([here](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)). This should standardize everything! If there is still a problem with formatting, please reopen this issue or create a new one. (Or talk in person :) )
