### ISSUE TITLE
Support deterministic ordering of check output for parallel checks

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#11]
Currently, this plugin will produce a non-deterministic ordering of the output when `gradle grade` is run for an assignment. My understanding is that this is due to the fact that the specified checks are run in parallel to to reduce the overall execution time of the tool. While I think that it is a really good idea to decrease response time, I anticipate that students would prefer to see all of the checks repeatedly displayed in the same order. Of course, I recognize that the failures at the bottom of the output are always displayed in order. But, I think that it would be useful to display all checks in order. Is there a way to buffer the results and then display them deterministically? Then, might there be a need to assign a unique idea to each one of the checks that this plugin runs?

**Comment by Michionlion** [comment]
It is certainly possible to order the checks, but for long-running checks it will result in no output bring shown -- I would prefer to do that rather than show both the in progress (to get immediate feedback) and ordered, buffered checks. If I recall correctly, checks already have an ordering mechanism which can be used. I'm not sure about this though, I will have to give it a bit more thought when I am able. Will try to resolve by Monday!

**Comment by gkapfham** [comment]
It is okay if you cannot resolve this on Monday. I wonder if one way to ensure the ordering of constraints is to pass in an identifier that the tool will then return back in the JSON. Otherwise, for instance, you might be able to record the timestamp at which you start a GatorGrader process and then use that data point to support the ordering of the checks. With that said, yes, I agree with your point about long-running checks. If we decide to keep allowing the results to display in a non-deterministic order, then we might consider including some type of output to explain that issue to the student using this plugin.

**Comment by gkapfham** [comment]
I am going to close this issue as I don't think that it is important to further resolve and/or discuss it.
