### ISSUE TITLE
Commands Produce Unparseable JSON Output

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#17]
I have to go quickly because I am running to a meeting, sorry for the brevity. I get this error message when I try to check the commits or execution of a program, for instance:

```
'/home/gkapfham/.local/share/virtualenvs/gatorgrader-gEDz9jHN/bin/python' '/home/gkapfham/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--commits' '10' produced unparsable json: Failed to parse json -- <eval>:1:38 Expected , but found recent
Java.asJSONCompatible(Traceback (most recent call last):
                                      ^ in <eval> at line number 1 at column number 38:
```

```
'/home/gkapfham/.local/share/virtualenvs/gatorgrader-gEDz9jHN/bin/python' '/home/gkapfham/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--command' 'gradle run' '--executes' produced unparsable json: Failed to parse json -- <eval>:1:38 Expected , but found recent
Java.asJSONCompatible(Traceback (most recent call last):
                                      ^ in <eval> at line number 1 at column nu
```

Here is the full configuration file to produce these errors:

```
---
name: computer-science-111-fall-2017-lab1
break: false
indent: 4
---
src/main:
    java:
        labone/DisplayOutput.java:
            --single 2 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 4
            --fragment "new Date(" --count 1
writing/reflection.md:
    mdl
    --paragraphs 1
    --words 200
--commits 10
--command "gradle run" --executes
```

Can you help to debug this? Is GatorGrader producing the wrong output? Please let me know!

**Comment by gkapfham** [comment]
Hello @Michionlion, I should note that the error message related to the checking of Git commit counts is one that I am going to classify as a bug for GatorGrader and not GatorGradle. I was testing to see if a check on Git commits would work when there was not a Git repository and, in fact, this does not work.
I will leave this issue open because I am still not sure how to handle a `gradle run`. But, the other concern about commit counting is a bug in GatorGrader that I will open and issue for later this week.

**Comment by gkapfham** [comment]
One additional debugging note, @Michionlion: I think that there is a problem with using `--executes` and it not producing the correct JSON output. If I try to count the lines in the output, this seems to work correctly. So, it seems that there is a bug in either `--executes` in GatorGrader or in the way that the plugin interprets the output of the command. I will investigate more and report back what I learn.

**Comment by Michionlion** [comment]
The bug for `--executes` is also a GatorGrader bug -- the output produced is an error trace!

```
Traceback (most recent call last):
  File "/home/m/mahlauheinerts/.local/share/gatorgrader/gatorgrader.py", line 10, in <module>
    exit_code = orchestrate.check(sys.argv[1:])
  File "/home/m/mahlauheinerts/.local/share/gatorgrader/gator/orchestrate.py", line 305, in check
    produced_output = report.output(output_list)
  File "/home/m/mahlauheinerts/.local/share/gatorgrader/gator/report.py", line 85, in output
    if util.is_json(output_as_list[FIRST]):
IndexError: list index out of range
```

Notably, without the `--json` flag the error is different:

```
Traceback (most recent call last):
  File "/home/m/mahlauheinerts/.local/share/gatorgrader/gatorgrader.py", line 10, in <module>
    exit_code = orchestrate.check(sys.argv[1:])
  File "/home/m/mahlauheinerts/.local/share/gatorgrader/gator/orchestrate.py", line 304, in check
    output_list = report.output_list(report.get_details(), OUTPUT_TYPE)
  File "/home/m/mahlauheinerts/.local/share/gatorgrader/gator/report.py", line 96, in output_list
    output_function(dictionary_result, created_output_list)
  File "/home/m/mahlauheinerts/.local/share/gatorgrader/gator/report.py", line 125, in output_text
    check = dictionary_result[CHECK]
KeyError: 'check'
```

I will create an issue for both of these in the GatorGrader repository.

**Comment by Michionlion** [comment]
I'm closing this as I think the root issues have been resolved or are being resolved in a different place.
