### ISSUE TITLE
Inconsistency in the phrasing of diagnostic messages in the output

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#19]
Currently, the Gradle plugin and the GatorGrader program produce diagnostic output that is slightly different. For instance, consider this output:

```
✔  The DisplayOutput.java in src/main/java/labone has at least 1 of the 'new Date(' fragment
✔  Repository has at least 10 commit(s)
✔  The DisplayOutput.java in src/main/java/labone has at least 2 single-line Java comment(s)
✔  The reflection.md in writing has at least 1 paragraph(s)
✔  The reflection.md in writing has at least 200 word(s) in every paragraph
✔  The file writing/reflection.md passes mdl
✔  The DisplayOutput.java in src/main/java/labone has at least 2 multiple-line Java comment(s)
✔  The DisplayOutput.java in src/main/java/labone has at least 4 of the 'println(' fragment
✔  The file writing/reflection.md passes proselint
✔  The content has at least 4 lines


        ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
        ┃ Passed 10/10 (100%) of checks for cmpsc-111-fall-2018-lab1! ┃
        ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

When the Gradle plugin runs a check with `mdl` it does not pass this through GatorGrader and rather runs the check on its own. However, the Gradle plugin using the phrase "The file" and the GatorGrader program simply writes "The ..." and gives the name of the file. Is there an easy way for the Gradle plugin to also use the format "entity in directory" and not use the word "the"? Otherwise, is there another approach that we can take to make the output as uniform as is possible? Okay, let me know what you think!

**Comment by Michionlion** [comment]
If we wanted to use the "entity in directory" format, we would have to parse the file path ourselves. It would certainly be possible, and should be something on our todo list!
