### ISSUE TITLE
Plugin does not produce a task with a description

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#20]
When I run a command like `gradle tasks --all` it produces the following output:

```
Other tasks
-----------
checkstyleMain - Run Checkstyle analysis for main classes
checkstyleTest - Run Checkstyle analysis for test classes
compileJava - Compiles main Java source.
compileTestJava - Compiles test Java source.
grade
processResources - Processes main resources.
processTestResources - Processes test resources.
runExploreDataTypes - Run the inclass.ExploreDataTypes program
```

Note that it seems as though the Gradle plugin does not offer a description property. Is there a way in which you can add this feature to the plugin? This will help people to understand what the plugin actually does. Please let me know if you have any questions about this feature request. Thanks!

**Comment by Michionlion** [comment]
This is certainly possible, and likely a simple API call. A good first issue!
