### ISSUE TITLE
Link in README does not work

### ISSUE THREAD

**Issue by ilikerustoo** [GatorEducator/gatorgradle#26]
The link to the sample lab :
"https://github.com/GatorEducator/gatorgrader-samplelab"

does not direct me anywhere (github 404).

**Comment by gkapfham** [comment]
Hello @ilikerustoo, thanks for raising this issue! Although it is not directly connected to the issue, I was also wondering if you would be willing to create a sample repository for a LaTeX document like the senior thesis proposal? If you have time to work on this in the next two weeks, that would be great. If you are interested but your schedule is tightly constrained right now, we could also wait until the middle of January and the start of February. Okay, let me know what you think!
