### ISSUE TITLE
Support HEREDOCS or equivalent for multi-line values in config

### ISSUE THREAD

**Issue by Michionlion** [GatorEducator/gatorgradle#27]
There may also need to be some updates to GatorGrader to support multi-line fragment checking, if it does not already work.

**Comment by gkapfham** [comment]
Hi @Michionlion, would this involve a multiple-line command-line argument? Can you please give me an example of what GatorGrader would need to support? Thanks!

**Comment by Michionlion** [comment]
Yes, this would be a multiple-line command-line argument, which the shell should be able to handle, but may need testing. Essentially, a fragment would need to be able to include the newline character.
