### ISSUE TITLE
Support serverless collection of data about executed checks

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#33]
Right now GatorGrader does not have a feature that will track information about which checks pass and fail across multiple runs. This means that it is very difficult to see patterns about the checks across all of the students in all of the courses for which GatorGrader is in use. 

One idea would be to adopt a serverless approach where a Python function is installed on Amazon. This function could store information in a Dynamo data store in an anonymous fashion. At the start, this function could store either the name or identifier of a check, details about an assignment/course, and a status about whether or not the check passed.

Note that this idea is an advanced feature that moves beyond the standard approach adopted by GatorGrader. However, the complete implementation of this feature would definitely make it easier for instructors who use GatorGrader to learn about how their students are doing in a course.

Finally, this feature requires careful thought about the security implications. By default, GatorGrader should not track this information. If the tracking of this information is enabled, then we need to think carefully about how we store and manage the data so that privacy is preserved. Also, when GatorGrader is adopted by others outside of Allegheny College we will need to further consider the mixture of data from multiple instructors and institutions.

**Comment by Michionlion** [comment]
I've transferred this issue to the GatorGradle repository for now, where we can figure out what this implementation should look like.

**Comment by gkapfham** [comment]
Thanks @Michionlion, I think that in the short term we might be able to delay the implementation of this feature.

**Comment by gkapfham** [comment]
I am writing to note that @Michionlion is now conducting a feasibility study for this feature. We have plans to move forward with its implementation, testing, and deployment. Thanks @Michionlion!
