### ISSUE TITLE
Implementing ChkTeX for linting LaTeX documents

### ISSUE THREAD

**Issue by leonardoz15** [GatorEducator/gatorgradle#38]
While the built in LaTeX checker does a good job, I think it would be beneficial to implement a linting tool before running any defined checks on the document. As an option I recommend the tool [ChkTex](http://www.nongnu.org/chktex/) which includes more semantic features than the default LaTeX checker. This would be an extremely easy way to keep all the LaTeX code stylistically uniform.

**Comment by Michionlion** [comment]
It should be in the GatorGradle repository, as code changes are required to accommodate this. I've transferred the issue!

**Comment by gkapfham** [comment]
Hi @Michionlion this might also be a good point to document in the README. Going forward, I can definitely imagine that we will need to add a wide variety of different tools that can be referenced in a GatorGrader configuration file. So, documenting how to extend the Gradle plugin would be useful.

**Comment by Michionlion** [comment]
This has actually already been implemented with the `executables` header; this does need to be added to the docs.
