### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#39]
It seems likely that the Gradle plugin for GatorGrader uses (directly or indirectly) the Nashorn engine. This leads to the warning message given in the title of this issue. Do you know what code in the Gradle plugin uses Nashorn? Is there a way to stop using Nashorn and adopt an alternative instead?

References:

https://github.com/junit-team/junit5/issues/1481
https://openjdk.java.net/jeps/335
https://jaxenter.com/nashorn-javascript-engine-deprecated-145320.html
https://www.infoworld.com/article/3291322/javascript/oracle-switch-now-from-nashorn-javascript-engine-to-graalvm.html
https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f

**Comment by gkapfham** [comment]
Hi @Michionlion, I see that it is in `CheckResult.java`. It looks like we can instead use graal.vm, right?

**Comment by Michionlion** [comment]
I can look into this, yes! All that is needed is parsing the JSON.

**Comment by gkapfham** [comment]
Hi @Michionlion, I'm wondering if we can use the fixing of this bug to illustrate how the "deploy" steps of the Gradle plugin work? I think that I could probably fix the bug myself &mdash; but I'm not sure if I could successfully deploy the plugin so that the newest version is available and in use! :wink:

**Comment by Michionlion** [comment]
Hi @gkapfham, that sounds like a good plan! As a side note, this can be added to the gradle parameters to suppress the warning: `-Dnashorn.args="--no-deprecation-warning"`.

**Comment by Michionlion** [comment]
Quick update: to disable this for a gradle project, add the following to `gradle.properties`.

```
systemProp.nashorn.args=--no-deprecation-warning
```

**Comment by Michionlion** [comment]
Sorry for the spam, but I've just learned one more critical piece: we can use the `ScriptEngineManager` to select at runtime the script engine to use, so that for versions older than 11 we can use `Nashorn`, and for version greater than or equal to 11 we can use `graal.vm`.

**Comment by gkapfham** [comment]
Hi @Michionlion, as a reminder: 

- We need to update the "starter repos" with the line that you suggested.
- We need to investigate whether or not using GraalVM is backwards compatible to older versions of Java.

**Comment by Michionlion** [comment]
So, to your second question, I think I have the answer. First, GraalVM is only available in Java 11 and later. However, using a scripting API in Java, we can choose between Nashorn and GraalVM at runtime.

**Comment by gkapfham** [comment]
Hello @Michionlion, I'm not sure that the suggestion of `systemProp.nashorn.args=--no-deprecation-warning` works correctly on my machine with this version of Gradle:

```
------------------------------------------------------------
Gradle 5.1
------------------------------------------------------------

Build time:   2019-01-02 18:57:47 UTC
Revision:     d09c2e354576ac41078c322815cc6db2b66d976e

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Linux 4.15.0-45-generic amd64
```

and this version of Java:

```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

In this case you *do not* get any formatted output when you run commands like `gradle grade`.

This means that you see a lot of messages like this one:

```
'/home/gkapfham/.local/share/virtualenvs/gatorgrader-gEDz9jHN/bin/python' '/home/gkapfham/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'src/www/' '--file' 'index.html' '--fragment' 'family=' '--count' '1' '--exact' produced unparsable json: Failed to parse json -- null:
"{"check": "The index.html in src/www/ has exactly 1 of the 'family=' fragment", "outcome": false, "diagnostic": "Found 0 fragment(s) in the output or the specified file"}"
{"check": "The index.html in src/www/ has exactly 1 of the 'family=' fragment", "outcome": false, "diagnostic": "Found 0 fragment(s) in the output or the specified file"}
```

I should point out that we are using Oracle JDK8 on the Travis CI runs. Perhaps this means that checks will not display correctly when they are running in Travis CI? I did not get time to check this, but the problem seems likely. Overall, I don't think that this property is backwards compatible for the deprecation warning, right? It seems to actually be disabling the use of the Nashorn JavaScript parser that we use for parsing the JSON. Thoughts on how to best proceed?

**Comment by gkapfham** [comment]
@Michionlion to your other point: it seems that we would have to take into account the version of Java through the scripting library and then pick the correct JSON parser from there. How hard is it, do you estimate, to implement this type of feature?

**Comment by Michionlion** [comment]
Hmm, certainly seems an oversight to have a system property like that disable Nashorn in Java 8 but for it to work correctly in Java 11. As to your second question, @gkapfham, I haven't done too much research. It seems from the blog posts discussing this issue, it shouldn't be too much work to get this added.

**Comment by gkapfham** [comment]
I am writing to confirm that using the system property does disable the use of Nashorn for parsing the JSON when you run the tool under Java 1.8 or 1.9. This means that we probably need to develop a new solution. Will this have to check for the JVM version and then use Nashorn or the GraalVM, @Michionlion?

**Comment by gkapfham** [comment]
fdfd

**Comment by gkapfham** [comment]
Hi @Michionlion, I think that you fully solved this issue, right? Can we close it now?

**Comment by Michionlion** [comment]
Yes, fully solved using regular expressions.
