### ISSUE TITLE
Proposed gradle task for file generation

### ISSUE THREAD

**Issue by Michionlion** [GatorEducator/gatorgradle#41]
A new task for Gradle should be added that generates the following:

* A language-generic `.travis.yml` that runs `gradle grade`, with comments linking to Travis CI documentation for different languages.
* A valid `gatorgrader.yml` that configures existence checks for current source sets, with comments linking to check documentation for additional configuration.

This task should be run with a simple interface such as `gradle gradeInit`, and should not override existing configuration (should do nothing if files exist).

**Comment by gkapfham** [comment]
This is a good idea, @Michionlion. Do you think that this fits into the timeline for this summer? Or, were you planning to save this for later because it is an "icing on the cake" kind of task?

**Comment by Michionlion** [comment]
This is probably something we can save for later, but I'll take a look at what it would take as well.

**Comment by gkapfham** [comment]
Hi @Michionlion, yeah, I agree that it is probably best to save this for later. One "halfway house" would be to either have this repository or the tool's debugging output point to all of the available sample repositories.
