### ISSUE TITLE
No CONTRIBUTING.md or CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Alex-Yarkosky** [GatorEducator/gatorgradle#42]
In order to improve the state of this project as an open source one, these proposed files should be included to make it easier to contribute in a productive way in accordance with the need outlined [here](https://opensource.guide/). I suggest that the Code of Conduct be taken from [here](https://www.contributor-covenant.org/) to avoid having to create one from scratch. GitHub also has some suggestions for making a Contributing file that can be found [here](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors). These files are also suggested on the [Community](https://github.com/GatorEducator/gatorgrader/community) page. Also, [here](https://github.com/AVMf/avmf/blob/master/CONTRIBUTING.md) is a `CONTRIBUTING.md` file that I made for another project, AVM*f*

**Comment by gkapfham** [comment]
Hello @Alex-Yarkosky, thanks for raising this issue, which I will soon try to resolve. @Michionlion, for parts of this request I will again reuse some of the content that we have (or will soon have) on GatorGrader. Let me know if that is not acceptable, okay?

**Comment by gkapfham** [comment]
Again, briefly I wanted to point out that GatorGrader has this type of documentation now.

https://github.com/GatorEducator/gatorgrader
