### ISSUE TITLE
Fix Gradle introduction to checks

### ISSUE THREAD

**Issue by alexheinle** [GatorEducator/gatorgradle#44]
Fix grammar mistakes in the introduction of Grader Gradle.

"Managing GatorGrader python dependencies..."

**Comment by Michionlion** [comment]
I've transferred this, but feel free to continue working on it if you feel the need. As a hint, [DependencyManager.java](https://github.com/GatorEducator/gatorgradle/blob/master/src/main/java/org/gatorgradle/internal/DependencyManager.java#L139) deals with a lot of those kind of print statements.
