### ISSUE TITLE
GatorGrader uninstall task

### ISSUE THREAD

**Issue by Michionlion** [GatorEducator/gatorgradle#45]
Create a task to delete the GatorGrader git repository.

**Comment by gkapfham** [comment]
Hi @Michionlion, I think that this is a good idea. If I am understanding the idea correctly, it should be possible to implement this by reusing some of the code already in the plugin, right? Is this on your radar screen for completion by the end of this month?

**Comment by Michionlion** [comment]
Yes, this will be one of the tasks I'll work towards!

**Comment by gkapfham** [comment]
Thanks for agreeing to work on this task, @Michionlion. Let me know if you need help with either development or testing as I am glad to assist!
