### ISSUE TITLE
Gradle logging

### ISSUE THREAD

**Issue by deedoubledub** [GatorEducator/gatorgradle#48]
The gradle daemon outputs logs to `~/.gradle/daemon/\<version\>/*.out.log`. These logs quickly grow out of control to hundreds of megabytes or gigabytes in size. Please implement a procedure to suppress or cleanup these logs.

Upstream issue: https://github.com/gradle/gradle/issues/2688
Example cleanup: https://discuss.gradle.org/t/gradle-daemon-produces-a-lot-of-logs/9905

**Comment by gkapfham** [comment]
Thanks for raising this issue @deedoubledub. @Michionlion is it important to note that the example cleanup link provided suggests a solution involving the code that would go in the build file itself. This means that it is something that we would introduce to a build file for a sample assignment (or, as talked about a long time ago, something that GatorGrader knows how to generate). Do you know of a way in which we can easily integrate this into the Gradle plugin itself?

**Comment by Michionlion** [comment]
As noted above, this is an issue endemic to Gradle itself, and fixes would require changes to a user's `build.gradle` file. As such, no fix is planned for GatorGradle.
