### ISSUE TITLE
Update documentation to improve and remove references to issues

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#7]
Currently the documentation in the `README.md` file contains references to issues that are no longer open. Moreover, since these issues are now resolved, it is possible to give full examples of the output produced by GatorGradle when used, for instance, with the sample lab. Overall, there are some small tweaks to the documentation that would make it easier for readers to understand what the tool does and how it works to use the configuration file to run checks and produce output.

**Comment by Michionlion** [comment]
I've updated documentation to provide better explanations, remove outdated text, and show some sample output.
