### ISSUE TITLE
Use a default name

### ISSUE THREAD

**Issue by mariakimheinert** [GatorEducator/gatorgradle#79]
If you omit the `name` attribute in the front matter of `gatorgrader.yml`, GatorGradle will fail.

```
> Configure project :
Configured GatorGradle 0.5.1

> Task :grade FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grade'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 352ms
1 actionable task: 1 executed
```

It would be helpful if GatorGradle would instead use a default name when one is not provided, such as the name of the folder that contains the `config` folder. This would be particularly helpful for those who commonly forget to update the `name` attribute when creating new assignments 😬 since the name in the resultant message can sometimes confuse students when it doesn't match the current assignment. It'd be great to just not have to set a name.

**Comment by Michionlion** [comment]
This will be solved by [GatorGrade](https://github.com/GatorEducator/gatorgrade), GatorGradle's successor.
