### ISSUE TITLE
Add documentation for the "--json" option

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#8]
Now that the GatorGrader supports the `--json` flag, the documentation for GatorGradle should be updated to reflect this feature. For instance, the example configuration file could show the `--json` flag in use. Also, the documentation should explain the benefits, if there are any obvious benefits to document, of this flag.

**Comment by Michionlion** [comment]
Right now GatorGradle actually adds the `--json` flag automatically, but when I update the documentation I will be sure to mention it somewhere. The user should not need to worry about whether to include it or not.

**Comment by gkapfham** [comment]
Cool, I think that we are up and running with this issue. I tested the `--json` flag with the sample lab and it seemed to work correctly in all of my manual tests. We can talk later about the testing strategy that I adopted in conjunction with using Pytest.
