### ISSUE TITLE
Do not indent the word "FAILURES" in the summary output

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#9]
I think that it might look better to not indent the word "FAILURE" since none of the other output on the screen is indented at exactly this level. Perhaps we could keep this word justified to the left and then leave the indenting only for the summary score at the bottom of the screen?

**Comment by Michionlion** [comment]
This has been changed, although the `-~-` bracketing the word were not removed. I'm unsure if there's a better way to do this, but it does look better without indentation!
